[package]
name = "nix-ld-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nix-ld-rs"
test = false

[[test]]
name = "tests"

[dependencies]
cfg-match = "0.2.1"
constcat = "0.3.0"
default-env = "0.1.1"
embedded-io = "0.5.0"
goblin = { version = "0.7.1", default-features = false, features = ["elf32", "elf64"] }
heapless = "0.7.16"
linux-raw-sys = { version = "0.4.3", default-features = false, features = ["no_std", "general", "errno"] }
log = "0.4.21"

[build-dependencies]
cc = "1.0.90"

[dev-dependencies]
cc = "1.0.90"
lazy_static = "1.4.0"
rstest = { version = "0.18.2", default-features = false }
tempfile = "3.10.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
debug = true

[features]
default = ["entry_trampoline"]

# Use a trampoline to revert our changes to LD_LIBRARY_PATH before executing the real program
entry_trampoline = []
